services:

  minio:
    image: minio/minio:latest
    restart: always
    networks:
      - inner
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - minio-data:/mnt/data
    environment:
      MINIO_VOLUMES: /mnt/data
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9090:9090"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 5s
      retries: 5
    command: minio server --console-address ":9090"

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    networks:
      - inner
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}

  nginx:
    image: nginx:stable
    restart: always
    depends_on:
      - cloudflared
    networks:
      inner:
      macvlan:
        ipv4_address: ${MINIO_IPV4_ADDRESS}
    ports:
      - "80"
      - "443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d
      - ./templates:/etc/nginx/templates
      - ./startup-hook.sh:/docker-entrypoint.d/startup-hook.sh:ro
      - acme-challenge:/var/www/certbot/:ro
      - letsencrypt:/etc/nginx/ssl/
    environment:
      MINIO_CONSOLE_DOMAIN: ${MINIO_CONSOLE_DOMAIN}
      MINIO_API_DOMAIN: ${MINIO_API_DOMAIN}

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - acme-challenge:/var/www/certbot/
      - letsencrypt:/etc/letsencrypt/

networks:
  inner:
  macvlan:
    name: macvlan
    driver: macvlan
    external: true

volumes:
  minio-data:
    name: minio-data
  acme-challenge:
  letsencrypt:
