name: Check by linters

on:
  push:
    branches: ["main"]

jobs:
  typos:
    runs-on: ubuntu-latest
    name: check misspelling by typos
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Run typos command
        shell: nix shell nixpkgs#typos --quiet --command bash {0}
        run: typos --hidden --exclude .git --format brief

  tflint:
    runs-on: ubuntu-latest
    name: lint opentofu code by tflint
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Run tflint command
        shell: nix shell nixpkgs#tflint --quiet --command bash {0}
        run: tflint --chdir ./infra --recursive
